name: Build Beta Version
run-name: ${{ github.actor }} builds application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'backend/pom.xml'

      - name: compile
        run: java -version
        working directory: backend

      -name: List files in the directory
        run: |
          ls ${{ github.workspace }}/backend

